### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Antlerkeke** [smilelight/lightKG#6]
您好，可以提供下/home/lightsmile/NLP/corpus/kg/baike/train.sample.csv'这个数据集吗，感谢！

**Comment by cxx-stack** [comment]
您好，可以提供下/home/lightsmile/NLP/corpus/kg/baike/train.sample.csv'这个数据集吗，感谢！!！

**Comment by smilelight** [comment]
抱歉了，各位。之前在忙别的事情没有及时回复。现在已经将几个任务的测试版数据集放到[data](https://github.com/smilelight/lightKG/tree/master/data)目录下了，你们将[examples](https://github.com/smilelight/lightKG/tree/master/examples)下的代码修改文件路径应该就能跑了。
