### ISSUE TITLE
lightkg安装失败

### ISSUE THREAD

**Issue by 742829191** [smilelight/lightKG#7]
请问是torch版本兼容的问题吗 用官网指令anaconda安装的torch 然后在terminal安装lighted时候一直报错失败  
错误如下
ERROR: Could not find a version that satisfies the requirement torch==1.0.0 (from lightKG) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.0.0 (from lightKG)

**Comment by 742829191** [comment]
而且pytorch的1.0.0好像没有常规渠道能下载 能不能指点一下

**Comment by smilelight** [comment]
已经修改啦，之前生成的requirements.txt文件指定了版本 @742829191

**Comment by 742829191** [comment]
> 已经修改啦，之前生成的requirements.txt文件指定了版本 @742829191

您好谢谢回答 现在code中的requirements.txt我已更换为>=1.0.0的版本 但是我使用pycharm编译器下载pip install -i https://pypi.douban.com/simple/ lightKG 这个命令的时候仍然ERROR: Could not find a version that satisfies the requirement torch==1.0.0 (from lightKG) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.0.0 (from lightKG)报无法找到1.0.0版本的错误
请问原因是什么

**Comment by smilelight** [comment]
@742829191 还是我的问题。。。好久没动这个项目了，刚才只更新了本地源码到Github，并没有上传到pypi，现在已经上传了。。。
![](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/lightKG更新至pypi.png)

**Comment by 742829191** [comment]
> @ 742829191还是我的问题......好久没动这个项目了，刚才只更新了本地源码到Github上，并没有上传到PyPI中，现在已经上传了...
非常感谢
但是pypi上的requirements还是=1.0.0 这是douban镜像还未更新的原因吗

**Comment by 742829191** [comment]
您好 现在已成功下载您更新的包 非常感谢
另如要用GPU训练是不是应下载CUDA版本pytorch？

**Comment by smilelight** [comment]
是的

**Comment by 742829191** [comment]
请问我将train的数据更换为开源的三元组数据集后处理速度急剧下降
![OGSSYO04T7I5({W`N$_{0A6](https://user-images.githubusercontent.com/67894224/86887829-c1f47780-c12b-11ea-8005-47640816a0f9.png)
这是什么原因 是tranE本身的缘故吗还是这个框架只能够训练使用小规模数据集

**Comment by smilelight** [comment]
@742829191 里面的程序是实验性的，设置的超参并没有针对大批量数据集，你可以自己去调整超参。
