### ISSUE TITLE
关于torchtext的vocab

### ISSUE THREAD

**Issue by 742829191** [smilelight/lightKG#8]
您好 经过几天学习您的代码之后 我尝试在您的代码基础上实现简单的基于梯度攻击的知识图谱攻击 
然后我想用求head+relation-tail关于head的导数以确定用于攻击的扰动 就应该用对应的词向量来运算
但是您代码中的self._entity_vocab貌似只是一个保存着词的列表 torch.tensor([self._entity_vocab.stoi[head]])获得的也只是一个关于该词的序号 那么我该怎么获得关于这个词的vectors的向量呢
新手入门尚在学习还请不吝赐教

**Comment by 742829191** [comment]
或者我用self._model(head_id, rel_id, tail_id))来代替f(head,relation,tail)来计算 但是self._model(head_id, rel_id, tail_id)计算实质是什么能给出以下 我在代码框架里并没有找到

**Comment by smilelight** [comment]
抱歉最近较忙，如果获取向量你可以看一下torchtext的教程，vocab对象的话有一个属性是vectors，里面包含相关向量信息。
关于函数计算，建议你再看一下代码，包括[lightKG/score_func.py at master · smilelight/lightKG](https://github.com/smilelight/lightKG/blob/master/lightkg/krl/utils/score_func.py)

**Comment by 742829191** [comment]
> 抱歉最近较忙，如果获取向量你可以看一下torchtext的教程，vocab对象的话有一个属性是vectors，里面包含相关向量信息。
> 关于函数计算，建议你再看一下代码，包括[lightKG/score_func.py at master · smilelight/lightKG](https://github.com/smilelight/lightKG/blob/master/lightkg/krl/utils/score_func.py)

万分感谢 我就是自己学习了网络上的torchtext的教程尝试提取vector 但是我使用self._entity_vocab.vectors的属性print出来是none 

然而self._entity_vocab是self._entity_vocab = entity_vocab和entity_vocab, relation_vocab = rl_tool.get_vocab(train_dataset, dev_dataset)中的ENTITY.build_vocab(*dataset)提取的ENTITY.vocab 按理说这个self._entity_vocab.vectors应该就是对应的向量，可是为什么我在train（）中尝试print结果确实无呢 会是因为三元组是中文的原因吗

![Uploading 2)EYP4O(AC6T]P4}UR0ZX5P.png…]()

![XVCNM5%T~X6YB7KQ%9T} SL](https://user-images.githubusercontent.com/67894224/87224880-748e3980-c3bb-11ea-8625-4da5b327c53b.png)

我所述的现象如上图所示

百忙之中叨扰还望见谅，抱歉一词更是折煞学生，还请您在闲暇之余能看看原因

**Comment by 742829191** [comment]
![OAY24{PFPFR6L7(3W RQ8)Q](https://user-images.githubusercontent.com/67894224/87224967-04cc7e80-c3bc-11ea-8d70-dd64b9976226.png)
 此为上述图1
